package diag

import (
	"slices"
	"strconv"
	"strings"
	"text/template"

	"cuelang.org/go/cue/token"
)

// SourceCache resolves a token.Pos to the source line it points at, with the
// 1-based line number and column. It returns ok=false when the position is
// unknown or the file is unavailable.
type SourceCache interface {
	LineAt(pos token.Pos) (line string, lineNum int, col int, ok bool)
}

// tabWidth is the number of spaces each tab expands to in rendered snippets.
// The caret's visual column is shifted by (tabsBefore * (tabWidth-1)) so the
// caret sits beneath the target byte after expansion.
const tabWidth = 4

// Render formats a Diagnostic into a multi-line, Rust-style string using src
// to fetch snippet lines. Missing source degrades to a "position unknown"
// marker; Render never panics on bad input per scope NF3.
func Render(d Diagnostic, src SourceCache) string {
	return RenderWithPalette(d, src, NoColorPalette{})
}

// RenderWithPalette formats a Diagnostic applying the given Palette to the
// severity word, caret runs, location segment, and hint footers. Legacy
// callers use Render which wraps this with NoColorPalette for byte-identical
// backwards compatibility.
func RenderWithPalette(d Diagnostic, src SourceCache, palette Palette) string {
	if palette == nil {
		palette = NoColorPalette{}
	}
	data := buildRenderData(d, src, palette)

	var b strings.Builder
	if err := renderTmpl.Execute(&b, data); err != nil {
		// Template/data shape drift is a programmer bug, not a runtime
		// condition — but NF3 forbids panics. Degrade to a terse marker so
		// the caller still gets an identifiable line.
		return "error: render template failure: " + err.Error() + "\n"
	}
	return b.String()
}

type renderData struct {
	Severity string
	Code     string
	Title    string
	Location string
	Gutter   int
	Labels   []labelData
	Help     string
	Footers  []string
}

type labelData struct {
	LineNum  int
	Line     string
	CaretCol int
	Carets   string
	Msg      string
	// Collapsed is true when this label shares its (file, line, col, len)
	// tuple with a previously-rendered label. Collapsed labels emit only an
	// aligned message row under the caret column of the first occurrence;
	// no snippet, no caret row.
	Collapsed bool
	// Synthetic is true when this label was generated by the Reason
	// renderer (e.g. RegexMismatch input echo) rather than from a real
	// source cache lookup. Synthetic frames render without a line-number
	// gutter.
	Synthetic bool
}

// frameData is the wire struct passed out of renderReasonText for secondary
// frames — a neutral shape that buildRenderData turns into labelData once it
// has a SourceCache to resolve arm spans against.
type frameData struct {
	// Synthetic input-echo frame carries its own expanded Line + CaretCol;
	// File/LineNum/Col/Len are zero.
	LineNum  int
	Line     string
	CaretCol int
	Carets   string
	Msg      string

	// FromArm frames carry a Span (File/LineNum/Col/Len) to be resolved
	// against the SourceCache at buildRenderData time.
	File    string
	Col     int
	Len     int
	FromArm bool
}

type resolvedLabel struct {
	label   Label
	line    string
	lineNum int
	col     int
	ok      bool
}

// spanKey identifies a (file, line, col, len) tuple for collapse detection.
// Two labels pointing at the same tuple share a frame: only the first
// emits the snippet + caret row; subsequent ones emit an aligned message row.
type spanKey struct {
	file   string
	line   int
	col    int
	length int
}

func buildRenderData(d Diagnostic, src SourceCache, palette Palette) renderData {
	if palette == nil {
		palette = NoColorPalette{}
	}
	_, primaryLineNum, primaryCol, primaryOK := src.LineAt(d.Primary.Pos)

	resolved := orderedLabels(d, src)

	labels := make([]labelData, 0, len(resolved))
	footers := []string{}
	help := d.Help
	// seen tracks previously-rendered spans by (file, line, col, length).
	// A later label matching any prior tuple renders as an aligned message
	// row only — skipping the snippet and caret to keep visual density low
	// when several messages attach to the same span (F7).
	seen := make(map[spanKey]int, len(resolved)) // value = visual caret column of first occurrence
	// maxLineNum tracks the widest line number across both real labels
	// and arm-derived pseudo-frames, so the gutter fits the whole
	// diagnostic regardless of emission order.
	maxLineNum := 1

	for _, r := range resolved {
		if !r.ok {
			continue
		}
		reasonMsgs, rframes, rfooters, helpOverride, suppress := dispatchReasons(r.label)
		footers = append(footers, rfooters...)
		if helpOverride != nil {
			help = emptyParentHelp(help) + *helpOverride
		}

		expanded, visualCol := expandTabs(r.line, r.col)
		key := spanKey{
			file:   r.label.Pos.Filename(),
			line:   r.lineNum,
			col:    r.col,
			length: r.label.Len,
		}
		if r.lineNum > maxLineNum {
			maxLineNum = r.lineNum
		}

		// Resolve messages: if the Label carries Reasons the first
		// becomes the caret-row text; remaining become aligned rows.
		// Empty Reasons path uses the Label's Msg as-is (NF5).
		primaryMsg := r.label.Msg
		extraMsgs := []string(nil)
		if len(reasonMsgs) > 0 {
			primaryMsg = reasonMsgs[0]
			extraMsgs = reasonMsgs[1:]
		}

		if firstCol, ok := seen[key]; ok {
			labels = append(labels, labelData{
				CaretCol:  firstCol,
				Msg:       primaryMsg,
				Collapsed: true,
			})
		} else {
			seen[key] = visualCol
			labels = append(labels, labelData{
				LineNum:  r.lineNum,
				Line:     expanded,
				CaretCol: visualCol,
				Carets:   palette.Caret(carets(r.label.Len)),
				Msg:      primaryMsg,
			})
		}
		// Stack any remaining reason messages as aligned rows under the
		// same caret column — same collapse visual layout, Reason-driven.
		for _, m := range extraMsgs {
			labels = append(labels, labelData{
				CaretCol:  seen[key],
				Msg:       m,
				Collapsed: true,
			})
		}

		// Emit reason-derived secondary frames. Synthetic frames render
		// without a gutter number; FromArm frames resolve against the
		// SourceCache and participate in the collapse seen map.
		for _, fr := range rframes {
			if suppress && fr.FromArm {
				continue
			}
			lbl, ln := frameToLabel(fr, seen, src)
			if ln > maxLineNum {
				maxLineNum = ln
			}
			// Secondary frames also honour the palette so caret colour
			// stays consistent across primary, arm, and synthetic frames.
			if lbl.Carets != "" {
				lbl.Carets = palette.Caret(lbl.Carets)
			}
			labels = append(labels, lbl)
		}
	}

	footers = append(footers, provenanceFooters(d)...)

	gutter := len(strconv.Itoa(maxLineNum))

	return renderData{
		Severity: palette.Severity(severityWord(d.Severity)),
		Code:     d.Code,
		Title:    d.Title,
		Location: locationLine(d.Primary, primaryLineNum, primaryCol, primaryOK, palette),
		Gutter:   gutter,
		Labels:   labels,
		Help:     help,
		Footers:  footers,
	}
}

// dispatchReasons folds a Label's Reasons slice into (caret/stacked messages,
// secondary frames, footers, help override, suppress-arms flag). Empty
// Reasons returns all zero values so the caller falls back to Label.Msg.
func dispatchReasons(l Label) (msgs []string, frames []frameData, footers []string, helpOverride *string, suppress bool) {
	if len(l.Reasons) == 0 {
		return nil, nil, nil, nil, false
	}
	for _, r := range l.Reasons {
		rr := renderReasonText(r, l.Msg)
		if rr.msg != "" {
			msgs = append(msgs, rr.msg)
		}
		frames = append(frames, rr.secondaryFrames...)
		footers = append(footers, rr.footers...)
		if rr.helpOverride != nil {
			helpOverride = rr.helpOverride
		}
		if rr.suppressExtraLabels {
			suppress = true
		}
	}
	return msgs, frames, footers, helpOverride, suppress
}

// emptyParentHelp derives the "= help: parent at <path> is an empty struct"
// prefix from the Help string that localize populated. The Help carries the
// parent path in "<path> has keys: " form; we peel it and assemble the new
// sentence here so render_reason.go stays dependency-free.
func emptyParentHelp(help string) string {
	path := parseEmptyParentPath(help)
	return "parent at " + path + " is an empty struct"
}

// frameToLabel converts a frameData (from renderReasonText) into a labelData,
// resolving FromArm frames against the SourceCache + collapse map so shared
// source lines stack cleanly. Synthetic frames bypass the collapse map —
// each carries its own expanded Line + CaretCol. The second return is the
// lineNum contributing to gutter width (0 when synthetic).
func frameToLabel(fr frameData, seen map[spanKey]int, src SourceCache) (label labelData, lineNum int) {
	if !fr.FromArm {
		carets := fr.Carets
		if carets == "" {
			carets = "^"
		}
		return labelData{
			LineNum:   fr.LineNum,
			Line:      fr.Line,
			CaretCol:  fr.CaretCol,
			Carets:    carets,
			Msg:       fr.Msg,
			Synthetic: true,
		}, 0
	}

	// FromArm: resolve against SourceCache using a synthesised token.Pos.
	// Since we only have a Span DTO (no token.Pos identity), we search
	// the SourceCache via a best-effort shim — callers pass fr.Line
	// populated if known; otherwise we fall back to a position-unknown
	// degrade that still carries the Msg.
	key := spanKey{
		file:   fr.File,
		line:   fr.LineNum,
		col:    fr.Col,
		length: fr.Len,
	}
	if firstCol, ok := seen[key]; ok {
		return labelData{
			CaretCol:  firstCol,
			Msg:       fr.Msg,
			Collapsed: true,
		}, fr.LineNum
	}

	// Look the span up in the SourceCache via a BySpan lookup if the
	// implementation supports it; otherwise degrade to an aligned
	// message-only row. We keep the Span-based SourceCache interface
	// narrow — the renderer accepts either a plain LineAt cache or the
	// extended BySpan interface.
	line, lineNum, col, ok := lookupBySpan(src, fr.File, fr.LineNum, fr.Col)
	if !ok {
		// Degrade: emit an aligned message row at col=fr.Col.
		seen[key] = fr.Col
		return labelData{
			LineNum:  fr.LineNum,
			Line:     "",
			CaretCol: fr.Col,
			Carets:   carets(fr.Len),
			Msg:      fr.Msg,
		}, fr.LineNum
	}

	expanded, visualCol := expandTabs(line, col)
	seen[key] = visualCol
	return labelData{
		LineNum:  lineNum,
		Line:     expanded,
		CaretCol: visualCol,
		Carets:   carets(fr.Len),
		Msg:      fr.Msg,
	}, lineNum
}

// SpanLookup is the optional extension interface a SourceCache may implement
// to resolve a (file, line, col) triple without a token.Pos handle. Used by
// DisjunctionFailed arm frames whose Spans carry only DTO coordinates.
type SpanLookup interface {
	LineAtSpan(file string, line, col int) (string, int, int, bool)
}

// lookupBySpan tries the SpanLookup extension first, then falls back to a
// degraded "not found" result. The plain LineAt signature cannot satisfy a
// DTO lookup, so FromArm frames without SpanLookup support render as
// message-only rows.
func lookupBySpan(src SourceCache, file string, line, col int) (snippet string, lineNum, byteCol int, ok bool) {
	if sl, ok := src.(SpanLookup); ok {
		return sl.LineAtSpan(file, line, col)
	}
	return "", 0, 0, false
}

func orderedLabels(d Diagnostic, src SourceCache) []resolvedLabel {
	out := make([]resolvedLabel, 0, 1+len(d.Notes))

	pl, pn, pc, pok := src.LineAt(d.Primary.Pos)
	out = append(out, resolvedLabel{
		label: d.Primary, line: pl, lineNum: pn, col: pc, ok: pok,
	})

	for _, n := range d.Notes {
		// Provenance-only Notes carry their coordinates inside the Span
		// payload, not as a token.Pos. They surface as footers via
		// provenanceFooters and never participate in the caret-frame
		// pipeline — skip them here so they aren't filtered as
		// invalid-Pos and silently dropped.
		if isProvenanceOnly(n) {
			continue
		}
		nl, nn, nc, nok := src.LineAt(n.Pos)
		out = append(out, resolvedLabel{
			label: n, line: nl, lineNum: nn, col: nc, ok: nok,
		})
	}

	slices.SortStableFunc(out, func(a, b resolvedLabel) int {
		return a.lineNum - b.lineNum
	})
	return out
}

// isProvenanceOnly reports whether n's Reasons are all Provenance entries.
// Such Notes carry their coordinates in the Span payload (Pos is invalid)
// and the renderer surfaces them as footers, not as caret frames.
func isProvenanceOnly(n Label) bool {
	if len(n.Reasons) == 0 {
		return false
	}
	for _, r := range n.Reasons {
		if _, ok := r.(Provenance); !ok {
			return false
		}
	}
	return true
}

// provenanceFooters extracts "= note: constraint introduced at <f:l:c>"
// footers from any Provenance Reasons on the Diagnostic's Notes. The
// underlying Note Labels carry the Span as the payload and an invalid
// token.Pos, so they bypass the SourceCache.LineAt filter that the caret-
// frame path applies — Provenance is metadata about constraint origin and
// never wants a caret of its own.
func provenanceFooters(d Diagnostic) []string {
	var out []string
	for _, n := range d.Notes {
		for _, r := range n.Reasons {
			p, ok := r.(Provenance)
			if !ok {
				continue
			}
			rr := renderProvenance(p)
			out = append(out, rr.footers...)
		}
	}
	return out
}

// expandTabs replaces tabs in src with tabWidth spaces and returns the visual
// column corresponding to the 1-based byte column col. Tabs AT the target
// column do not count toward the shift (strict-before semantics); the column
// scan is clamped to len(src) so a col past end-of-line is safe.
func expandTabs(src string, col int) (expanded string, visualCol int) {
	limit := max(min(col-1, len(src)), 0)
	tabsBefore := strings.Count(src[:limit], "\t")
	expanded = strings.ReplaceAll(src, "\t", strings.Repeat(" ", tabWidth))
	return expanded, col + tabsBefore*(tabWidth-1)
}

func severityWord(s Severity) string {
	switch s {
	case SeverityWarning:
		return "warning"
	case SeverityNote:
		return "note"
	default:
		return "error"
	}
}

func locationLine(primary Label, lineNum, col int, ok bool, palette Palette) string {
	if palette == nil {
		palette = NoColorPalette{}
	}
	if !ok {
		return "  --> position unknown"
	}
	coords := primary.Pos.Filename() + ":" + strconv.Itoa(lineNum) + ":" + strconv.Itoa(col)
	return "  --> " + palette.Location(coords)
}

func carets(n int) string {
	if n <= 0 {
		return "^"
	}
	return strings.Repeat("^", n)
}

var renderTmpl = template.Must(template.New("diag").
	Funcs(template.FuncMap{
		"pad":    func(n int) string { return strings.Repeat(" ", n) },
		"lineNo": func(gutter, n int) string { return leftPad(strconv.Itoa(n), gutter) },
	}).
	Parse(diagnosticTemplate))

func leftPad(s string, width int) string {
	if len(s) >= width {
		return s
	}
	return strings.Repeat(" ", width-len(s)) + s
}

const diagnosticTemplate = `{{.Severity}}[{{.Code}}]: {{.Title}}
{{.Location}}
{{pad .Gutter}} |
{{range $i, $l := .Labels}}{{if $l.Collapsed}}{{pad $.Gutter}} |{{pad $l.CaretCol}}{{$l.Msg}}
{{else if $l.Synthetic}}{{if $i}}{{pad $.Gutter}} |
{{end}}{{pad $.Gutter}} | {{$l.Line}}
{{pad $.Gutter}} |{{pad $l.CaretCol}}{{$l.Carets}}{{with $l.Msg}} {{.}}{{end}}
{{else}}{{if $i}}{{pad $.Gutter}} |
{{end}}{{lineNo $.Gutter $l.LineNum}} | {{$l.Line}}
{{pad $.Gutter}} |{{pad $l.CaretCol}}{{$l.Carets}}{{with $l.Msg}} {{.}}{{end}}
{{end}}{{end}}{{with .Help}}{{pad $.Gutter}} |
{{pad $.Gutter}} = help: {{.}}
{{end}}{{range .Footers}}{{pad $.Gutter}} {{.}}
{{end}}`
